imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    imagesTrip_directory: '%kernel.root_dir%/../web/uploads/imageTrips'

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
        cookie_lifetime: ~
    fragments: ~
    http_method_override: true
    assets: ~
    #php_errors:
    #  log: false

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
            # other form themes
            - 'VichUploaderBundle:Form:fields.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    delivery_address: lotfi.idir@gmail.com
    transport: '%mailer_transport%'
    encryption: ssl
    port: 465
    host: smtp.gmail.com
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

ivory_google_map:
    map:
        debug: "%kernel.debug%"
        api_key: AIzaSyCnX_MphD697QVoFq4mKvnpxhpyHQm2vOg

fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address: lotfi.idir@gmail.com
        sender_name: Travel mate
    registration:
        form:
            type: AppBundle\Form\RegistrationType
        confirmation:
            from_email:
                  address: lotfi.idir@gmail.com
                  sender_name: Travel mate
    resetting:
        email:
            from_email:
                address: lotfi.idir@gmail.com
                sender_name: Travel mate
    profile:
        form:
            type: AppBundle\Form\RegistrationType

vich_uploader:
    db_driver: orm
    mappings:
            user_image:
                uri_prefix:         /uploads/user/profilepics
                upload_destination: '%kernel.root_dir%/../web/uploads/user/profilepics'