app:
    resource: '@AppBundle/Controller/'
    type: annotation

search:
    path:     trips/search
    defaults: { _controller: AppBundle:Search:show }

trip_create:
    path:      trip/creer
    defaults:  { _controller: AppBundle:Trip:create }
    methods: [GET, POST]

